### PR TITLE
Fix text highlights missing

### PR DESCRIPTION
**Pull request by another-hodler**
This fixes 
https://github.com/joaofnfernandes/glacierprotocol.github.io/issues/12

### CODE REVIEW

**Comment by diogomonica** [comment]
Thanks for Thanks for the contributions @another-hodler . Did you generate the PDF to see how it comes out? I'm concerned the <span> won't actually work well.

**Comment by diogomonica** [comment]
@another-hodler LGTM but we have some merge conflicts now.

Will try to schedule a point release for next week to include some other fixes merged to master in the meantime.

**Comment by another-hodler** [comment]
@diogomonica Resolved the conflict. Please note that in some cases I had to use HTML tags and inline styles to make font smaller to fit page width or to wrap content.

It seems like what we need is beyond markdown capabilities and maybe something like https://asciidoctor.org/docs/user-manual/#compared-to-markdown would be a better option.

**Comment by diogomonica** [comment]
LGTM

**Pull request merged**
